In [1]:
import numpy as np

# 1. Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

# 2. Array properties
print("\nArray Properties:")
print(f"Shape of arr1: {arr1.shape}")
print(f"Shape of arr2: {arr2.shape}")
print(f"Size of arr1: {arr1.size}")
print(f"Size of arr2: {arr2.size}")
print(f"Data type of arr1: {arr1.dtype}")
print(f"Data type of arr2: {arr2.dtype}")

# 3. Basic operations on arrays
# a) Element-wise addition
arr_add = arr1 + 5
print("\nElement-wise addition:")
print(arr_add)

# b) Element-wise multiplication
arr_mult = arr1 * 2
print("\nElement-wise multiplication:")
print(arr_mult)

# c) Dot product (for 1D arrays)
arr3 = np.array([10, 20, 30, 40, 50])
dot_product = np.dot(arr1, arr3)
print("\nDot product of arr1 and arr3:")
print(dot_product)

# d) Matrix multiplication (for 2D arrays)
arr4 = np.array([[7, 8], [9, 10], [11, 12]])
matrix_mult = np.dot(arr2, arr4)
print("\nMatrix multiplication of arr2 and arr4:")
print(matrix_mult)

# 4. Array indexing and slicing
print("\nArray Indexing and Slicing:")
print(f"First element of arr1: {arr1[0]}")
print(f"Last element of arr1: {arr1[-1]}")
print(f"First row of arr2: {arr2[0, :]}")
print(f"Second column of arr2: {arr2[:, 1]}")

# 5. Reshaping arrays
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr5_reshaped = arr5.reshape((2, 4))
print("\nReshaped Array (2x4):")
print(arr5_reshaped)

# 6. Aggregation functions
print("\nAggregation Functions:")
print(f"Sum of elements in arr1: {np.sum(arr1)}")
print(f"Mean of elements in arr1: {np.mean(arr1)}")
print(f"Max element in arr1: {np.max(arr1)}")
print(f"Min element in arr1: {np.min(arr1)}")

# 7. Concatenating arrays
arr6 = np.array([6, 7, 8, 9, 10])
arr_concat = np.concatenate((arr1, arr6))
print("\nConcatenated Array:")
print(arr_concat)

# 8. Splitting arrays
arr_split = np.array_split(arr_concat, 3)
print("\nSplitted Arrays:")
for i, sub_array in enumerate(arr_split):
    print(f"Sub-array {i+1}: {sub_array}")

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Array Properties:
Shape of arr1: (5,)
Shape of arr2: (2, 3)
Size of arr1: 5
Size of arr2: 6
Data type of arr1: int64
Data type of arr2: int64

Element-wise addition:
[ 6  7  8  9 10]

Element-wise multiplication:
[ 2  4  6  8 10]

Dot product of arr1 and arr3:
550

Matrix multiplication of arr2 and arr4:
[[ 58  64]
 [139 154]]

Array Indexing and Slicing:
First element of arr1: 1
Last element of arr1: 5
First row of arr2: [1 2 3]
Second column of arr2: [2 5]

Reshaped Array (2x4):
[[1 2 3 4]
 [5 6 7 8]]

Aggregation Functions:
Sum of elements in arr1: 15
Mean of elements in arr1: 3.0
Max element in arr1: 5
Min element in arr1: 1

Concatenated Array:
[ 1  2  3  4  5  6  7  8  9 10]

Splitted Arrays:
Sub-array 1: [1 2 3 4]
Sub-array 2: [5 6 7]
Sub-array 3: [ 8  9 10]


In [11]:
import numpy as np

# 1. Array Creation
# Creating a 1D array
arr1 = np.array([10, 20, 30, 40, 50,60])

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Creating arrays with specific values
zeros_array = np.zeros((3, 3))  # 3x3 array of zeros
ones_array = np.ones((2, 4))    # 2x4 array of ones
range_array = np.arange(0, 10, 2)  # Array with values from 0 to 10 with step 2

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\nArray of Zeros:")
print(zeros_array)

print("\nArray of Ones:")
print(ones_array)

print("\nArray with Range Values:")
print(range_array)

# 2. Indexing and Slicing
# Accessing elements in 1D array
first_element = arr1[0]
last_element = arr1[-1]

# Accessing elements in 2D array
element_2_2 = arr2[1, 1]  # Element at second row, second column
first_row = arr2[0, :]    # Entire first row
second_column = arr2[:, 1]  # Entire second column

print("\nFirst Element of arr1:", first_element)
print("Last Element of arr1:", last_element)

print("\nElement at 2nd row, 2nd column of arr2:", element_2_2)
print("First Row of arr2:", first_row)
print("Second Column of arr2:", second_column)

# 3. Reshaping Arrays
# Reshaping 1D array into a 2x3 2D array
arr1_reshaped = arr1.reshape((2,3))
print("\nReshaped 1D Array (2x3):")
print(arr1_reshaped)

# Flattening a 2D array back into a 1D array
arr2_flattened = arr2.flatten()
print("\nFlattened 2D Array:")
print(arr2_flattened)

# 4. Applying Mathematical Operations
# Element-wise addition
added_array = arr1 + 10
print("\nElement-wise Addition (arr1 + 10):")
print(added_array)

# Element-wise multiplication
multiplied_array = arr1 * 2
print("\nElement-wise Multiplication (arr1 * 2):")
print(multiplied_array)

# Square root of each element
sqrt_array = np.sqrt(arr1)
print("\nSquare Root of arr1:")
print(sqrt_array)

# Summation of all elements in arr2
sum_arr2 = np.sum(arr2)
print("\nSum of all elements in arr2:")
print(sum_arr2)

# Transposing a 2D array
arr2_transposed = np.transpose(arr2)
print("\nTransposed arr2:")
print(arr2_transposed)

1D Array:
[10 20 30 40 50 60]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array with Range Values:
[0 2 4 6 8]

First Element of arr1: 10
Last Element of arr1: 60

Element at 2nd row, 2nd column of arr2: 5
First Row of arr2: [1 2 3]
Second Column of arr2: [2 5 8]

Reshaped 1D Array (2x3):
[[10 20 30]
 [40 50 60]]

Flattened 2D Array:
[1 2 3 4 5 6 7 8 9]

Element-wise Addition (arr1 + 10):
[20 30 40 50 60 70]

Element-wise Multiplication (arr1 * 2):
[ 20  40  60  80 100 120]

Square Root of arr1:
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]

Sum of all elements in arr2:
45

Transposed arr2:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
import numpy as np

# Sample data: Exam scores of students in three different subjects
scores = np.array([
    [85, 78, 92],  # Student 1
    [88, 90, 80],  # Student 2
    [90, 88, 85],  # Student 3
    [72, 95, 88],  # Student 4
    [80, 85, 91]   # Student 5
])

# 1. Compute Summary Statistics

# Mean
mean_scores = np.mean(scores, axis=0)  # Mean of each subject (column-wise)
print("Mean Scores (Subject-wise):", mean_scores)

# Median
median_scores = np.median(scores, axis=0)  # Median of each subject (column-wise)
print("Median Scores (Subject-wise):", median_scores)

# Standard Deviation
std_deviation = np.std(scores, axis=0)  # Standard deviation of each subject (column-wise)
print("Standard Deviation (Subject-wise):", std_deviation)

# Sum
total_scores = np.sum(scores, axis=1)  # Total score for each student (row-wise)
print("Total Scores (Student-wise):", total_scores)

# 2. Grouping Data and Performing Aggregations

# Let's assume the students belong to two different groups: Group A and Group B
# Group A: Students 1, 2, 3; Group B: Students 4, 5
group_labels = np.array(['A', 'A', 'A', 'B', 'B'])

# Calculate the mean score for each group in each subject
group_a_scores = scores[group_labels == 'A']
group_b_scores = scores[group_labels == 'B']

mean_group_a = np.mean(group_a_scores, axis=0)
mean_group_b = np.mean(group_b_scores, axis=0)

print("\nMean Scores (Group A):", mean_group_a)
print("Mean Scores (Group B):", mean_group_b)

# Calculate the total score for each group across all subjects
total_group_a = np.sum(group_a_scores)
total_group_b = np.sum(group_b_scores)

print("\nTotal Scores (Group A):", total_group_a)
print("Total Scores (Group B):", total_group_b)

# Perform an aggregation to find the highest score in each subject for each group
max_group_a = np.max(group_a_scores, axis=0)
max_group_b = np.max(group_b_scores, axis=0)

print("\nMaximum Scores (Group A):", max_group_a)
print("Maximum Scores (Group B):", max_group_b)

Mean Scores (Subject-wise): [83.  87.2 87.2]
Median Scores (Subject-wise): [85. 88. 88.]
Standard Deviation (Subject-wise): [6.4498062  5.63560112 4.35430821]
Total Scores (Student-wise): [255 258 263 255 256]

Mean Scores (Group A): [87.66666667 85.33333333 85.66666667]
Mean Scores (Group B): [76.  90.  89.5]

Total Scores (Group A): 776
Total Scores (Group B): 511

Maximum Scores (Group A): [90 90 92]
Maximum Scores (Group B): [80 95 91]
